# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

import pandas

import snakemake

configfile: "config/config.yaml"

snakemake.utils.validate(config, "schemas/config.yaml")

samples = pandas.read_csv(config["samples"])

snakemake.utils.validate(samples, "schemas/samples.yaml")

samples = samples.set_index("sample")

units = pandas.read_csv(config["units"])

snakemake.utils.validate(units, "schemas/units.yaml")

units = units.set_index(["sample", "unit"])

include: "rules/busparse.smk"
include: "rules/bustools.smk"
include: "rules/common.smk"
include: "rules/eisar.smk"
include: "rules/genomepy.smk"
include: "rules/gffread.smk"
include: "rules/kallisto.smk"
include: "rules/resources.smk"
include: "rules/salmon.smk"
include: "rules/singlecellexperiment.smk"
include: "rules/star.smk"

ALIGNERS = ["kallisto", "salmon", "star"]

SAMPLES = samples["sample"]

rule all:
    input:
        expand("results/singlecellexperiment/{aligner}/{sample}.rds", aligner = ALIGNERS, sample = SAMPLES)